[package]
name = "rust-todo-cli"
version = "0.2.3-beta.2"
edition = "2024"
repository = "https://github.com/TiaoFeng/rust-todo-cli"
description = "A CLI tool for managing to-do lists"
readme = "README.md"
keywords = ["cli", "tool", "todo"]
license = "MIT"

[[bin]]
name = "rstodo"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"]}
serde = { version = "1", features = ["derive"]}
serde_json = { version = "1"}
chrono = { version = "0.4.45" , features = ["serde"]}
comfy-table = "8.0.0"
dirs = "6"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
